//! `aas shim` — make the bare provider CLI (`claude`, `codex`, …) use the aas-active account.
//!
//! `switch` normally materializes the active credential into the provider's native store, but
//! that is not always possible: Claude's long-lived `setup-token` credential is only accepted
//! through `CLAUDE_CODE_OAUTH_TOKEN`, so `claude::switch_to` deliberately skips the native write
//! for it. A shim closes the gap uniformly — the bare command re-enters through
//! `aas exec <active>`, which already knows how to hand each credential shape to the agent.

use crate::exec::{agent_bin, SHIM_BIN_ENV};
use crate::ui;
use aas_core::naming::normalize_provider_key;
use aas_core::platform::asx_config_dir;
use std::path::{Path, PathBuf};

/// Providers whose native CLI `aas exec` can launch.
pub const SHIMMABLE: &[&str] = &["claude", "codex", "grok", "pi"];

#[derive(clap::Subcommand, Debug)]
pub enum ShimAction {
    /// Install shims (default: every supported CLI found on PATH).
    Install {
        #[arg(value_name = "PROVIDER")]
        providers: Vec<String>,
    },
    /// Remove installed shims (default: all).
    Uninstall {
        #[arg(value_name = "PROVIDER")]
        providers: Vec<String>,
    },
    /// Show installed shims and whether they actually take precedence on PATH.
    Status,
}

/// Environment that means the caller has already chosen a backend or credential for `provider`.
///
/// Wrappers that point the agent at a third-party Anthropic-compatible endpoint (Kimi, GLM, an
/// internal proxy) export their own base URL and token and then invoke the agent by name — which
/// now finds the shim. Re-entering through `aas exec` would strip those credentials
/// (`scrub_inherited_credentials`) and substitute the active account's, leaving the call pointed
/// at the third-party endpoint while authenticating as Anthropic. An explicit choice must win.
fn override_env(provider: &str) -> &'static [&'static str] {
    match provider {
        "claude" => &[
            "CLAUDE_CONFIG_DIR",
            "CLAUDE_CODE_OAUTH_TOKEN",
            "ANTHROPIC_API_KEY",
            "ANTHROPIC_AUTH_TOKEN",
            "ANTHROPIC_BASE_URL",
        ],
        "codex" => &["CODEX_HOME", "OPENAI_API_KEY", "OPENAI_BASE_URL"],
        "grok" => &["GROK_HOME", "XAI_API_KEY", "GROK_API_KEY"],
        "pi" => &["PI_CODING_AGENT_DIR", "PI_AUTH_JSON"],
        _ => &[],
    }
}

pub fn shim_dir() -> PathBuf {
    asx_config_dir().join("shims")
}

fn sh_quote(path: &Path) -> String {
    format!("'{}'", path.to_string_lossy().replace('\'', "'\\''"))
}

fn same_dir(a: &Path, b: &Path) -> bool {
    match (a.canonicalize(), b.canonicalize()) {
        (Ok(a), Ok(b)) => a == b,
        _ => a == b,
    }
}

fn is_executable(path: &Path) -> bool {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::metadata(path)
            .map(|meta| meta.is_file() && meta.permissions().mode() & 0o111 != 0)
            .unwrap_or(false)
    }
    #[cfg(not(unix))]
    {
        path.is_file()
    }
}

/// True when `dir` sits inside the system temp directory.
fn under_temp_dir(dir: &Path) -> bool {
    let tmp = std::env::temp_dir();
    match (dir.canonicalize(), tmp.canonicalize()) {
        (Ok(dir), Ok(tmp)) => dir.starts_with(tmp),
        _ => dir.starts_with(&tmp),
    }
}

/// Locate the provider's real CLI, skipping our own shim directory so a reinstall can never
/// point a shim at itself.
///
/// The system temp directory is skipped for the same reason: wrappers that re-launch the agent
/// install a per-session copy of it there (cmux wraps `codex` this way), so recording one both
/// sends every launch back through the wrapper and goes stale the moment that directory is
/// cleaned up.
fn real_binary(bin: &str) -> Option<PathBuf> {
    let shims = shim_dir();
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path)
        .filter(|dir| !same_dir(dir, &shims) && !under_temp_dir(dir))
        .map(|dir| dir.join(bin))
        .find(|candidate| is_executable(candidate))
}

fn shim_body(provider: &str, real: &Path, aas: &Path) -> String {
    let real = sh_quote(real);
    let aas = sh_quote(aas);
    let mut s = String::new();
    s.push_str("#!/bin/sh\n");
    s.push_str("# Generated by `aas shim install` - do not edit.\n");
    s.push_str("# Routes the bare CLI through whichever account `aas` has active.\n\n");
    s.push_str(
        "# Re-entry guard: `aas exec` resolves the agent through PATH and would otherwise\n",
    );
    s.push_str("# find this shim again, recursing forever.\n");
    s.push_str("if [ -n \"${AAS_SHIM:-}\" ]; then\n");
    s.push_str(&format!("  exec {real} \"$@\"\n"));
    s.push_str("fi\n\n");
    s.push_str(
        "# An explicit backend choice in the environment wins: a wrapper that already set its\n",
    );
    s.push_str("# own endpoint or credential must not be rewritten to the active account.\n");
    s.push_str(&format!(
        "for _aas_var in {}; do\n",
        override_env(provider).join(" ")
    ));
    s.push_str("  eval \"_aas_val=\\${$_aas_var:-}\"\n");
    s.push_str("  if [ -n \"$_aas_val\" ]; then\n");
    s.push_str(&format!("    exec {real} \"$@\"\n"));
    s.push_str("  fi\n");
    s.push_str("done\n\n");
    s.push_str("# No active account (or aas unavailable) must never block the real CLI.\n");
    s.push_str(&format!(
        "active=$({aas} active {provider} 2>/dev/null) || active=''\n"
    ));
    s.push_str("if [ -z \"$active\" ]; then\n");
    s.push_str(&format!("  exec {real} \"$@\"\n"));
    s.push_str("fi\n\n");
    s.push_str("AAS_SHIM=1\n");
    s.push_str("export AAS_SHIM\n");
    s.push_str(
        "# Hand the resolved CLI to `aas exec` so it does not look the agent up on PATH again:\n",
    );
    s.push_str(
        "# a third-party wrapper around the same CLI sits ahead of this shim and would run\n",
    );
    s.push_str("# a second time, prepending its own flags twice.\n");
    s.push_str(&format!("{}={real}\n", SHIM_BIN_ENV));
    s.push_str(&format!("export {}\n", SHIM_BIN_ENV));
    s.push_str("# `--` forwards every argument verbatim, so agent flags (-d/--debug/-b) are not\n");
    s.push_str("# eaten by aas's own exec options.\n");
    s.push_str(&format!("exec {aas} exec \"$active\" -- \"$@\"\n"));
    s
}

fn resolve_targets(providers: &[String]) -> anyhow::Result<Vec<String>> {
    if providers.is_empty() {
        return Ok(SHIMMABLE.iter().map(|p| (*p).to_string()).collect());
    }
    providers
        .iter()
        .map(|raw| {
            let key = normalize_provider_key(raw);
            if SHIMMABLE.contains(&key.as_str()) {
                Ok(key)
            } else {
                anyhow::bail!("no native CLI to shim for provider '{raw}'")
            }
        })
        .collect()
}

fn set_executable(path: &Path) -> std::io::Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755))?;
    }
    let _ = path;
    Ok(())
}

pub fn install(providers: &[String]) -> anyhow::Result<()> {
    let dir = shim_dir();
    std::fs::create_dir_all(&dir)?;
    let aas = std::env::current_exe()?;
    let mut installed = 0usize;

    for provider in resolve_targets(providers)? {
        let Some(bin) = agent_bin(&provider) else {
            continue;
        };
        let Some(real) = real_binary(bin) else {
            ui::hint(format!("{provider}: `{bin}` is not on PATH — skipped"));
            continue;
        };
        let path = dir.join(bin);
        std::fs::write(&path, shim_body(&provider, &real, &aas))?;
        set_executable(&path)?;
        ui::success(format!("{bin} → {}", real.display()));
        installed += 1;
    }

    if installed == 0 {
        ui::warn("no shims installed — none of the supported CLIs were found on PATH.");
        return Ok(());
    }
    println!();
    ui::hint(format!("shim dir: {}", dir.display()));
    if path_has_precedence(&dir) {
        ui::success("shim directory already precedes the real CLIs on PATH.");
    } else {
        ui::warn("the shim directory is not ahead of the real CLIs on PATH yet — add:");
        println!("  export PATH=\"{}:$PATH\"", dir.display());
    }
    Ok(())
}

pub fn uninstall(providers: &[String]) -> anyhow::Result<()> {
    let dir = shim_dir();
    let mut removed = 0usize;
    for provider in resolve_targets(providers)? {
        let Some(bin) = agent_bin(&provider) else {
            continue;
        };
        let path = dir.join(bin);
        match std::fs::remove_file(&path) {
            Ok(()) => {
                ui::success(format!("removed {bin}"));
                removed += 1;
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error.into()),
        }
    }
    if removed == 0 {
        ui::hint("no shims to remove.");
    }
    Ok(())
}

/// Names we have actually written a shim for.
fn installed_shims(dir: &Path) -> Vec<&'static str> {
    SHIMMABLE
        .iter()
        .filter_map(|provider| agent_bin(provider))
        .filter(|bin| dir.join(bin).exists())
        .collect()
}

/// True when the shim directory comes before the real CLI of every shim we installed.
///
/// Only installed shims count: a provider we do not shim may legitimately sit earlier on PATH,
/// and letting it drag the answer to "no" reports a broken setup that works fine. Per-session
/// wrappers under the temp directory are ignored for the same reason — one intercepts the name
/// first, but it re-launches the agent and so still arrives here.
fn path_has_precedence(dir: &Path) -> bool {
    let Some(path) = std::env::var_os("PATH") else {
        return false;
    };
    let entries: Vec<PathBuf> = std::env::split_paths(&path).collect();
    let Some(shim_at) = entries.iter().position(|entry| same_dir(entry, dir)) else {
        return false;
    };
    installed_shims(dir).into_iter().all(|bin| {
        match entries.iter().position(|entry| {
            !same_dir(entry, dir) && !under_temp_dir(entry) && is_executable(&entry.join(bin))
        }) {
            Some(real_at) => shim_at < real_at,
            None => true,
        }
    })
}

pub fn status() -> anyhow::Result<()> {
    let dir = shim_dir();
    println!("{} {}", ui::heading("shim dir:"), dir.display());
    let on_path = std::env::var_os("PATH")
        .map(|path| std::env::split_paths(&path).any(|entry| same_dir(&entry, &dir)))
        .unwrap_or(false);
    let installed = installed_shims(&dir);
    if installed.is_empty() {
        ui::hint("no shims installed — run `aas shim install`.");
        return Ok(());
    }
    if !on_path {
        ui::warn("not on PATH — installed shims are inert.");
        println!("  export PATH=\"{}:$PATH\"", dir.display());
    } else if path_has_precedence(&dir) {
        ui::success("on PATH, ahead of the real CLIs.");
    } else {
        ui::warn("on PATH but *after* a real CLI — that CLI still wins.");
    }

    for bin in installed {
        let real = real_binary(bin)
            .map(|path| path.display().to_string())
            .unwrap_or_else(|| "(real CLI not found)".into());
        println!("  {bin:<8} → {real}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn body_hands_the_resolved_binary_to_exec() {
        let body = shim_body(
            "codex",
            Path::new("/opt/bin/codex"),
            Path::new("/usr/local/bin/aas"),
        );
        assert!(body.contains("AAS_SHIM_BIN='/opt/bin/codex'\nexport AAS_SHIM_BIN\n"));
        // Set after every fall-through exec, so only the `aas exec` hand-off sees it.
        let handoff = body.find("AAS_SHIM_BIN=").unwrap();
        assert!(handoff > body.rfind("exec '/opt/bin/codex' \"$@\"").unwrap());
        assert!(handoff < body.find("exec '/usr/local/bin/aas' exec").unwrap());
    }

    #[test]
    fn per_session_wrappers_are_not_mistaken_for_an_installation() {
        let wrapper = std::env::temp_dir().join("aas-shim-test-wrapper");
        std::fs::create_dir_all(&wrapper).unwrap();
        assert!(under_temp_dir(&wrapper));
        assert!(!under_temp_dir(Path::new("/usr/local/bin")));
        let _ = std::fs::remove_dir_all(&wrapper);
    }
}
